# config/cloudinary.yml
development:
  cloud_name: ENV['CLOUD_NAME']
  api_key: ENV['api_key']
  api_secret: ENV['api_secret']

production:
  cloud_name: ENV['CLOUD_NAME']
  api_key: ENV['api_key]
  api_secret: ENV['api_secret']