# config/cloudinary.yml
development:
  cloud_name: "dwrltsmzw"
  api_key: ENV["API_KEY"]
  api_secret: ENV["API_SECRET"],

production:
  :cloud_name: "dwrltsmzw"
  api_key: ENV["API_KEY"]
  api_secret: ENV["API_SECRET"],